/**
 * FieldKernel.js
 *
 * The propagation and interference rules of the quantum field layer.
 *
 * Philosophy:
 *   There is no grid. There is a medium.
 *   The medium only exists where there is perturbation.
 *   Perturbations are not objects — they are informational disturbances
 *   that propagate, interfere, and either stabilize or dissolve.
 *
 *   A quark is a vortex: a closed loop in the data flow of the medium.
 *   A proton is constructive interference of three vortices.
 *   An electron is the Chladni pattern generated by nuclear vibration
 *   on the computable space around it. It is never an object.
 *
 * The kernel defines:
 *   1. How perturbations propagate through the medium
 *   2. How they interfere (constructive / destructive)
 *   3. How nuclear frequency is inferred from real element data
 *   4. How the Chladni pattern (orbital) emerges from that frequency
 *
 * Input: real element data (ionization energy, electronegativity, etc.)
 * Output: ω_nuclear, orbital radii, interference map
 *
 * Units: pm (world units), eV (energy), normalized frequencies [0..1]
 */


// ─── Hydrogen as reference baseline ──────────────────────────────────────────
// All frequencies are normalized relative to hydrogen.
// H: Z=1, ionization=13.5984 eV, electronegativity=2.2, r_atomic=53 pm

const H_REF = {
    ionization_eV:      13.5984,
    electronegativity:  2.2,
    effective_Z:        1.0,
    radius_pm:          53,
    binding_energy_MeV: 0,       // free proton — no binding
};

// Frequency scale factor: maps eV → simulation frequency units
// Chosen so H has ω = 1.0 (everything relative to hydrogen)
const FREQ_SCALE = 1.0 / H_REF.ionization_eV;

// ─── Chladni harmonic mode table ──────────────────────────────────────────────
// Maps quantum shell occupation {s, p, d, f} to 3D harmonic mode indices.
// These determine the nodal structure of the orbital pattern.
// (m, n, l) → number of nodal surfaces in each dimension
const HARMONIC_MODES = {
    s: { radialNodes: 0, angularNodes: 0, symmetry: 'spherical'    },
    p: { radialNodes: 0, angularNodes: 1, symmetry: 'axial'        },
    d: { radialNodes: 0, angularNodes: 2, symmetry: 'quadrupolar'  },
    f: { radialNodes: 0, angularNodes: 3, symmetry: 'octupolar'    },
};


// ─── FieldKernel ──────────────────────────────────────────────────────────────

export class FieldKernel {

    /**
     * Infer nuclear vibration frequency from real element data.
     *
     * The chain:
     *   ionization_energy → base frequency (how tightly the nucleus holds)
     *   electronegativity → shielding modulation (how much it pulls outward)
     *   effective_Z       → vortex intensity (core charge density)
     *   binding_energy    → confinement depth (nuclear binding modifies ω)
     *
     * Result: ω_nuclear — a normalized frequency [~0.1 .. ~10]
     * where H = 1.0 and heavier elements scale naturally.
     *
     * @param {Object} elementData   Parsed element JSON
     * @returns {number}             ω_nuclear in simulation units
     */
    static inferNuclearFrequency(elementData) {
        const atomic  = elementData.atomic_structure;
        const nuclear = elementData.nuclear_and_environmental;

        const ionization   = atomic.ionization_energy_eV   ?? H_REF.ionization_eV;
        const electronegativity = atomic.electronegativity  ?? H_REF.electronegativity;
        const effectiveZ   = atomic.effective_nuclear_charge ?? 1.0;
        const bindingMeV   = nuclear.nuclear_binding_energy_mev ?? 0;

        // Base frequency: ionization energy normalized to H
        // Higher ionization → nucleus vibrates faster → tighter orbital
        const ω_base = ionization * FREQ_SCALE;

        // Shielding factor: electronegativity modulates how much of ω
        // reaches the outer field. High EN = less shielding = tighter pattern.
        // Normalized to H's electronegativity.
        const shield = electronegativity / H_REF.electronegativity;

        // Effective charge amplification: more protons = stronger vortex
        const chargeAmp = Math.sqrt(effectiveZ / H_REF.effective_Z);

        // Nuclear binding correction: binding energy per nucleon shifts ω
        // (binding energy in MeV, ionization in eV — scale accordingly)
        // For H (free proton): binding = 0, no correction.
        const Z = elementData.identity.number;
        const bindingPerNucleon = Z > 1
            ? (bindingMeV / Z) / 1000   // MeV/nucleon → GeV scale, normalize
            : 0;
        const bindingCorrection = 1.0 + bindingPerNucleon * 0.1;

        const ω_nuclear = ω_base * shield * chargeAmp * bindingCorrection;

        return ω_nuclear;
    }


    /**
     * Compute the Chladni orbital pattern for a nucleus.
     *
     * A Chladni pattern is the set of nodal surfaces where
     * destructive interference zeroes out the field amplitude.
     * Between the nodes: constructive zones → where "electrons" stabilize.
     *
     * Returns a descriptor of the pattern — not geometry.
     * The renderer interprets this into visual form.
     *
     * @param {Object} elementData
     * @param {number} ω_nuclear     From inferNuclearFrequency()
     * @returns {Object}             Chladni pattern descriptor
     */
    static computeOrbitalPattern(elementData, ω_nuclear) {
        const atomic  = elementData.atomic_structure;
        const qn      = atomic.quantum_numbers ?? { s: 0, p: 0, d: 0, f: 0 };
        const shells  = atomic.shells ?? [1];
        const r_atomic = atomic.radius_atomic_pm ?? H_REF.radius_pm;
        const r_vdw    = atomic.vanderwaals_radius_pm ?? r_atomic * 2;

        // Active orbital types from quantum numbers
        const activeOrbitals = [];
        for (const [type, count] of Object.entries(qn)) {
            if (count > 0) {
                activeOrbitals.push({
                    type,
                    count,
                    mode: HARMONIC_MODES[type],
                });
            }
        }

        // Radial shell structure: each shell is a Chladni ring
        // Shell radius scales with ω_nuclear — tighter nucleus = smaller shells
        const shellRadii = shells.map((electrons, i) => {
            const n = i + 1; // principal quantum number
            // Bohr-like scaling: r_n = r_atomic * n² / Z_eff / ω_nuclear
            // But we use real r_atomic as anchor, not computed from scratch
            return {
                n,
                electrons,
                radius: r_atomic * (n * n) / ω_nuclear,
                // Nodes within this shell from orbital type
                angularNodes: activeOrbitals
                    .filter(o => o.mode)
                    .reduce((sum, o) => sum + o.mode.angularNodes, 0),
            };
        });

        // Apantallamiento (shielding) per shell:
        // Inner electrons shield outer ones from the nuclear vortex.
        // This determines how loosely outer electrons are bound.
        const shieldingPerShell = shellRadii.map((shell, i) => {
            // Slater-like: each inner electron contributes 0.85 shielding
            // electrons in same shell: 0.35
            const innerElectrons = shellRadii
                .slice(0, i)
                .reduce((sum, s) => sum + s.electrons, 0);
            const sameShellElectrons = shell.electrons - 1;
            return {
                ...shell,
                shielding: innerElectrons * 0.85 + sameShellElectrons * 0.35,
                effectiveZ: elementData.identity.number
                    - (innerElectrons * 0.85 + sameShellElectrons * 0.35),
            };
        });

        return {
            ω_nuclear,
            r_atomic,
            r_vanderwaals: r_vdw,
            shells: shieldingPerShell,
            activeOrbitals,
            // Total number of nodal surfaces in the pattern
            // More nodes = more complex Chladni figure
            totalNodes: activeOrbitals.reduce(
                (sum, o) => sum + (o.mode?.angularNodes ?? 0), 0
            ),
            // Pattern symmetry — determines 3D shape of the Chladni figure
            dominantSymmetry: activeOrbitals.length > 0
                ? activeOrbitals[activeOrbitals.length - 1].mode?.symmetry
                : 'spherical',
        };
    }


    /**
     * Evaluate field amplitude at a point in space relative to a nucleus.
     *
     * This is the core of the Chladni emergence:
     * φ(r, θ, φ) = Σ_shells [ A_n · exp(-r/r_n) · cos(ω·t + θ_phase) · Y(θ,φ) ]
     *
     * Where Y(θ,φ) is a simplified spherical harmonic — the angular pattern
     * that creates the nodal structure of the orbital.
     *
     * @param {THREE.Vector3} point      World position to evaluate
     * @param {THREE.Vector3} nucleus    Nucleus position
     * @param {Object}        pattern    From computeOrbitalPattern()
     * @param {number}        time       Simulation time for phase
     * @returns {number}                 Field amplitude at point [-1..1]
     */
    static evaluateField(point, nucleus, pattern, time) {
        const dx = point.x - nucleus.x;
        const dy = point.y - nucleus.y;
        const dz = point.z - nucleus.z;
        const r  = Math.sqrt(dx*dx + dy*dy + dz*dz);

        if (r < 1e-6) return 1.0; // at nucleus: maximum amplitude

        // Spherical coordinates
        const cosTheta = dz / r;
        const phi_angle = Math.atan2(dy, dx);

        let amplitude = 0;

        for (const shell of pattern.shells) {
            if (r > shell.radius * 3) continue; // beyond influence, skip

            // Radial decay: exponential envelope centered on shell radius
            const radialEnvelope = Math.exp(
                -Math.abs(r - shell.radius) / (shell.radius * 0.3)
            );

            // Angular pattern from orbital symmetry
            let angular = 1.0;
            const sym = pattern.dominantSymmetry;

            if (sym === 'axial') {
                // p-orbital: one nodal plane (xy plane)
                angular = Math.abs(cosTheta);
            } else if (sym === 'quadrupolar') {
                // d-orbital: two nodal cones
                angular = Math.abs(3 * cosTheta * cosTheta - 1) / 2;
            } else if (sym === 'octupolar') {
                // f-orbital: three nodal surfaces
                angular = Math.abs(5 * cosTheta * cosTheta * cosTheta
                    - 3 * cosTheta) / 2;
            }
            // spherical: angular = 1.0 (no modulation)

            // Phase oscillation at nuclear frequency
            const phase = pattern.ω_nuclear * time + phi_angle;
            const oscillation = Math.cos(phase);

            // Shielding reduces amplitude for outer shells
            const shieldFactor = 1.0 / (1.0 + shell.shielding * 0.1);

            amplitude += radialEnvelope * angular * oscillation * shieldFactor;
        }

        return Math.max(-1, Math.min(1, amplitude));
    }


    /**
     * Find constructive interference zones between two nuclear patterns.
     * This is where molecular bonds emerge — no bond object, just zones
     * where both nuclei's fields add constructively.
     *
     * @param {THREE.Vector3} posA
     * @param {Object}        patternA
     * @param {THREE.Vector3} posB
     * @param {Object}        patternB
     * @param {number}        time
     * @param {number}        samples   Number of points to sample along axis
     * @returns {Object[]}              Constructive zones with position + strength
     */
    static findConstructiveZones(posA, patternA, posB, patternB, time, samples = 20) {
        const zones = [];
        const axis  = { x: posB.x - posA.x, y: posB.y - posA.y, z: posB.z - posA.z };
        const dist  = Math.sqrt(axis.x**2 + axis.y**2 + axis.z**2);

        for (let i = 0; i <= samples; i++) {
            const t = i / samples;
            const pt = {
                x: posA.x + axis.x * t,
                y: posA.y + axis.y * t,
                z: posA.z + axis.z * t,
            };

            const ampA = FieldKernel.evaluateField(pt, posA, patternA, time);
            const ampB = FieldKernel.evaluateField(pt, posB, patternB, time);

            // Constructive: both amplitudes same sign and significant
            const interference = ampA * ampB;
            if (interference > 0.1) {
                zones.push({
                    position: pt,
                    strength: interference,
                    t,        // parametric position along A→B axis
                });
            }
        }

        return zones;
    }


    /**
     * Infer bond character from two orbital patterns.
     * Emerges from frequency ratio and symmetry — not hardcoded.
     *
     * @param {Object} patternA
     * @param {Object} patternB
     * @returns {Object}  { character, strength, type }
     */
    static inferBondCharacter(patternA, patternB) {
        const freqRatio = Math.min(patternA.ω_nuclear, patternB.ω_nuclear)
                        / Math.max(patternA.ω_nuclear, patternB.ω_nuclear);

        // Frequency match → stronger resonance → covalent character
        // Frequency mismatch → one dominates → ionic character
        const covalentCharacter = freqRatio;
        const ionicCharacter    = 1.0 - freqRatio;

        // Symmetry compatibility
        const sameSymmetry = patternA.dominantSymmetry === patternB.dominantSymmetry;

        return {
            covalentCharacter,
            ionicCharacter,
            type: ionicCharacter > 0.5 ? 'ionic' : 'covalent',
            // Bond strength from overlap of van der Waals radii
            strength: freqRatio * (sameSymmetry ? 1.2 : 0.8),
        };
    }
}
